Catch up Libplanet's upstream & limit block size
planetarium/NineChronicles.Standalone pull request #189
Opened 2020-11-24 12:41 UTC by dahlia

This should be merged *after* <https://github.com/planetarium/lib9c/pull/220> & <https://github.com/planetarium/libplanet/pull/1102> are merged.

2020-11-24 13:22 UTC, riemannulus approved these changes

2020-11-24 13:22 UTC, riemannulus requested changes
Build seems failed 😢

2020-11-26 02:28 UTC, dahlia commented
@planetarium/libplanet Please review this again?

2020-11-26 02:30 UTC, moreal approved these changes

2020-11-26 04:23 UTC, riemannulus approved these changes

2020-11-26 04:24 UTC, merged